const assert = require("node:assert/strict")
const { readFileSync } = require("node:fs")
const { resolve } = require("node:path")

const ROOT = resolve(__dirname, "..")
const workflow = readFileSync(
  resolve(ROOT, ".github/workflows/update-plugin-catalog.yml"),
  "utf8"
)
const registry = readFileSync(resolve(ROOT, "plugins.txt"), "utf8")
const readme = readFileSync(resolve(ROOT, "README.md"), "utf8")
const expectedUrls = [
  "https://github.com/brianblakely/blink.git",
  "https://github.com/brianblakely/omacal.git",
  "https://github.com/brianblakely/omahud.git",
  "https://github.com/brianblakely/omaled.git",
  "https://github.com/brianblakely/omanews.git",
  "https://github.com/brianblakely/omanote.git",
  "https://github.com/brianblakely/omasnap.git",
  "https://github.com/brianblakely/omastonk.git",
  "https://github.com/brianblakely/peek.git",
  "https://github.com/mwikala/omarchy-world-time.git"
]
let passed = 0

function test(name, callback) {
  callback()
  passed += 1
  process.stdout.write(`ok ${passed} - ${name}\n`)
}

test("plugins.txt contains the ten canonical standalone URLs in deterministic order", () => {
  assert.equal(registry.endsWith("\n"), true)
  assert.deepEqual(registry.trimEnd().split("\n"), expectedUrls)
})

test("workflow has only the requested registry push and manual triggers", () => {
  assert.match(workflow, /^on:\n {2}push:\n {4}paths:\n {6}- plugins\.txt\n {2}workflow_dispatch:\n/m)
  assert.doesNotMatch(workflow, /\bpull_request:/)
  assert.doesNotMatch(workflow, /\bschedule:/)
})

test("workflow grants the least repository permission needed to write README", () => {
  assert.match(workflow, /^permissions:\n {2}contents: write\n/m)
  assert.equal((workflow.match(/\bcontents:\s*write\b/g) || []).length, 1)
})

test("workflow uses the current official checkout major and local generator", () => {
  assert.match(workflow, /uses: actions\/checkout@v6/)
  assert.match(workflow, /run: node scripts\/generate-plugin-catalog\.mjs/)
  assert.equal((workflow.match(/\buses:/g) || []).length, 1)
})

test("workflow rejects unrelated changes and stages only README before pushing", () => {
  assert.match(workflow, /git status --porcelain --untracked-files=all -- \. '\:\(exclude\)README\.md'/)
  const addTargets = [...workflow.matchAll(/^\s*git add -- (.+)$/gm)]
    .map(match => match[1])
  assert.deepEqual(addTargets, ["README.md"])
  assert.match(workflow, /\[\[ "\$\(git diff --cached --name-only\)" == "README\.md" \]\]/)
  assert.match(workflow, /^\s*git push$/m)
})

test("README exposes exactly one marker-owned generated catalog region", () => {
  assert.equal(
    readme.split("<!-- BEGIN GENERATED PLUGIN CATALOG -->").length - 1,
    1
  )
  assert.equal(
    readme.split("<!-- END GENERATED PLUGIN CATALOG -->").length - 1,
    1
  )
  assert.match(
    readme,
    /Generated by scripts\/generate-plugin-catalog\.mjs from plugins\.txt/
  )
})

process.stdout.write(`${passed} catalog workflow tests passed\n`)
