const assert = require("node:assert/strict")
const {
  chmodSync,
  copyFileSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  statSync,
  writeFileSync
} = require("node:fs")
const { tmpdir } = require("node:os")
const { join, resolve } = require("node:path")
const { spawnSync } = require("node:child_process")

const ROOT = resolve(__dirname, "..")
const GENERATOR = join(ROOT, "scripts", "generate-plugin-catalog.mjs")
const TEMP = mkdtempSync(join(tmpdir(), "okomart-generator-test-"))
const BEGIN = "<!-- BEGIN GENERATED PLUGIN CATALOG -->"
const END = "<!-- END GENERATED PLUGIN CATALOG -->"
let passed = 0

process.on("exit", () => rmSync(TEMP, { recursive: true, force: true }))

function test(name, callback) {
  callback()
  passed += 1
  process.stdout.write(`ok ${passed} - ${name}\n`)
}

function createHarness(name) {
  const root = join(TEMP, name)
  const bin = join(root, "bin")
  const fixtures = join(root, "fixtures")
  mkdirSync(bin, { recursive: true })
  mkdirSync(fixtures, { recursive: true })

  const fakeGit = join(bin, "git")
  writeFileSync(fakeGit, `#!/usr/bin/env node
const fs = require("node:fs")
const path = require("node:path")
const args = process.argv.slice(2)
const separator = args.indexOf("--")
if (args[0] !== "clone" || separator < 0 || args.length !== separator + 3)
  process.exit(91)
const url = args[separator + 1]
const destination = args[separator + 2]
fs.appendFileSync(process.env.CLONE_LOG, url + "\\n")
if (url === process.env.FAIL_CLONE_URL) process.exit(92)
const slug = new URL(url).pathname.split("/").pop().replace(/\\.git$/, "")
const fixture = path.join(process.env.FIXTURE_ROOT, slug + ".json")
if (!fs.existsSync(fixture)) process.exit(93)
if (url === process.env.SLEEP_CLONE_URL)
  Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 5000)
fs.mkdirSync(destination, { recursive: true })
fs.copyFileSync(fixture, path.join(destination, "manifest.json"))
`)
  chmodSync(fakeGit, 0o755)

  const registry = join(root, "plugins.txt")
  const readme = join(root, "README.md")
  const cloneLog = join(root, "clones.log")
  writeFileSync(cloneLog, "")
  return { root, bin, fixtures, registry, readme, cloneLog }
}

function writeManifest(harness, slug, manifest) {
  const target = join(harness.fixtures, `${slug}.json`)
  if (typeof manifest === "string") writeFileSync(target, manifest)
  else writeFileSync(target, `${JSON.stringify(manifest)}\n`)
}

function runGenerator(harness, extraEnvironment = {}) {
  return spawnSync(process.execPath, [
    GENERATOR,
    harness.registry,
    harness.readme
  ], {
    encoding: "utf8",
    env: {
      ...process.env,
      PATH: `${harness.bin}:${process.env.PATH}`,
      CLONE_LOG: harness.cloneLog,
      FIXTURE_ROOT: harness.fixtures,
      ...extraEnvironment
    }
  })
}

function fixtureReadme(generated = "old generated content") {
  return [
    "# Fixture",
    "",
    "Before the generated region.",
    BEGIN,
    generated,
    END,
    "After the generated region.",
    ""
  ].join("\n")
}

test("generates a sorted, escaped table and preserves text outside its markers", () => {
  const harness = createHarness("success")
  writeFileSync(harness.registry, [
    "https://example.test/zeta.git",
    "https://example.test/alpha.git",
    ""
  ].join("\r\n"))
  writeManifest(harness, "alpha", {
    name: "Alpha | [Tool]",
    author: "A *uthor*",
    description: "Uses <unsafe> & backslash \\ and\nnew line."
  })
  writeManifest(harness, "zeta", {
    name: "Zeta `Code`",
    author: "Zed_Name",
    description: "Bang! ~~"
  })
  writeFileSync(harness.readme, fixtureReadme())

  const result = runGenerator(harness)
  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /Updated README\.md with 2 plugins\./)
  assert.deepEqual(
    readFileSync(harness.cloneLog, "utf8").trim().split("\n"),
    [
      "https://example.test/alpha.git",
      "https://example.test/zeta.git"
    ]
  )

  const expected = String.raw`# Fixture

Before the generated region.
<!-- BEGIN GENERATED PLUGIN CATALOG -->
<!-- Generated by scripts/generate-plugin-catalog.mjs from plugins.txt. -->

| Plugin | Author | Description |
| --- | --- | --- |
| [Alpha \| \[Tool\]](<https://example.test/alpha.git>) | A \*uthor\* | Uses &lt;unsafe&gt; &amp; backslash \\ and new line. |
| [Zeta \`Code\`](<https://example.test/zeta.git>) | Zed\_Name | Bang\! \~\~ |
<!-- END GENERATED PLUGIN CATALOG -->
After the generated region.
`
  assert.equal(readFileSync(harness.readme, "utf8"), expected)

  const inode = statSync(harness.readme).ino
  writeFileSync(harness.cloneLog, "")
  const second = runGenerator(harness)
  assert.equal(second.status, 0, second.stderr)
  assert.match(second.stdout, /Verified README\.md with 2 plugins\./)
  assert.equal(statSync(harness.readme).ino, inode)
})

test("rejects blank, duplicate, non-HTTPS, and non-.git registry entries before cloning", () => {
  const harness = createHarness("invalid-registry")
  writeManifest(harness, "alpha", {
    name: "Alpha",
    author: "Author",
    description: "Description"
  })
  const original = fixtureReadme()
  writeFileSync(harness.readme, original)

  const cases = [
    ["https://example.test/alpha.git\n\n", /line 2 is blank/],
    [
      "https://example.test/alpha.git\nhttps://example.test/alpha.git\n",
      /duplicate URL/
    ],
    ["http://example.test/alpha.git\n", /must use https/],
    ["https://example.test/alpha\n", /must end in \.git/],
    [
      "https://example.test/%2e%2e/alpha.git\n",
      /canonical public DNS URL/
    ],
    [
      "https://127.000.000.001/alpha.git\n",
      /canonical URL form|canonical public DNS URL/
    ],
    ["https://[:::]/alpha.git\n", /valid URL/],
    [
      "https://example.test/café.git\n",
      /canonical URL form|canonical repository path/
    ]
  ]
  for (const [registry, error] of cases) {
    writeFileSync(harness.registry, registry)
    writeFileSync(harness.cloneLog, "")
    const result = runGenerator(harness)
    assert.notEqual(result.status, 0)
    assert.match(result.stderr, error)
    assert.equal(readFileSync(harness.cloneLog, "utf8"), "")
    assert.equal(readFileSync(harness.readme, "utf8"), original)
  }
})

test("requires nonblank string name, author, and description metadata", () => {
  const harness = createHarness("invalid-metadata")
  const url = "https://example.test/alpha.git"
  writeFileSync(harness.registry, `${url}\n`)
  const original = fixtureReadme()
  writeFileSync(harness.readme, original)

  const cases = [
    [{ author: "Author", description: "Description" }, /field 'name'/],
    [{ name: "Alpha", author: 42, description: "Description" }, /field 'author'/],
    [{ name: "Alpha", author: "Author", description: "   " }, /field 'description'/],
    ["{", /not valid JSON/]
  ]
  for (const [manifest, error] of cases) {
    writeManifest(harness, "alpha", manifest)
    const result = runGenerator(harness)
    assert.notEqual(result.status, 0)
    assert.match(result.stderr, error)
    assert.equal(readFileSync(harness.readme, "utf8"), original)
  }
})

test("refuses missing, duplicate, inline, or reversed marker ownership before cloning", () => {
  const harness = createHarness("invalid-markers")
  writeFileSync(harness.registry, "https://example.test/alpha.git\n")
  writeManifest(harness, "alpha", {
    name: "Alpha",
    author: "Author",
    description: "Description"
  })
  const cases = [
    `# Missing\n${BEGIN}\n`,
    `# Duplicate\n${BEGIN}\n${BEGIN}\n${END}\n`,
    `# Inline ${BEGIN}\n${END}\n`,
    `# Reversed\n${END}\n${BEGIN}\n`
  ]
  for (const readme of cases) {
    writeFileSync(harness.readme, readme)
    writeFileSync(harness.cloneLog, "")
    const result = runGenerator(harness)
    assert.notEqual(result.status, 0)
    assert.equal(readFileSync(harness.cloneLog, "utf8"), "")
    assert.equal(readFileSync(harness.readme, "utf8"), readme)
  }
})

test("leaves README untouched when a repository cannot be cloned", () => {
  const harness = createHarness("clone-failure")
  const url = "https://example.test/alpha.git"
  writeFileSync(harness.registry, `${url}\n`)
  writeManifest(harness, "alpha", {
    name: "Alpha",
    author: "Author",
    description: "Description"
  })
  const original = fixtureReadme()
  writeFileSync(harness.readme, original)

  const result = runGenerator(harness, { FAIL_CLONE_URL: url })
  assert.notEqual(result.status, 0)
  assert.match(result.stderr, /Could not clone plugin repository/)
  assert.equal(readFileSync(harness.readme, "utf8"), original)
})

test("validates and enforces a bounded per-repository clone timeout", () => {
  const harness = createHarness("clone-timeout")
  const url = "https://example.test/alpha.git"
  writeFileSync(harness.registry, `${url}\n`)
  writeManifest(harness, "alpha", {
    name: "Alpha",
    author: "Author",
    description: "Description"
  })
  const original = fixtureReadme()
  writeFileSync(harness.readme, original)

  for (const value of ["0", "1.5", "601"]) {
    writeFileSync(harness.cloneLog, "")
    const invalid = runGenerator(harness, {
      OKOMART_CATALOG_CLONE_TIMEOUT_SECONDS: value
    })
    assert.notEqual(invalid.status, 0)
    assert.match(invalid.stderr, /integer from 1 to 600/)
    assert.equal(readFileSync(harness.cloneLog, "utf8"), "")
  }

  const timedOut = runGenerator(harness, {
    OKOMART_CATALOG_CLONE_TIMEOUT_SECONDS: "1",
    SLEEP_CLONE_URL: url
  })
  assert.notEqual(timedOut.status, 0)
  assert.match(timedOut.stderr, /Timed out cloning plugin repository/)
  assert.equal(readFileSync(harness.readme, "utf8"), original)
})

process.stdout.write(`${passed} catalog generator tests passed\n`)
