const assert = require("node:assert/strict")
const { readFileSync } = require("node:fs")
const { resolve } = require("node:path")

const ROOT = resolve(__dirname, "..")
const workflow = readFileSync(
  resolve(ROOT, ".github/workflows/update-plugin-catalog.yml"),
  "utf8"
)
const registry = readFileSync(resolve(ROOT, "plugins.txt"), "utf8")
const readme = readFileSync(resolve(ROOT, "README.md"), "utf8")
const generator = readFileSync(
  resolve(ROOT, "scripts/generate-plugin-catalog.mjs"),
  "utf8"
)
const backend = readFileSync(resolve(ROOT, "bin/okomart"), "utf8")
const marketplaceRegistryUrl = "https://raw.githubusercontent.com/HANCORE-linux/omarchy-plugin-marketplace/refs/heads/main/registry.json"
const expectedUrls = [
  "https://github.com/brianblakely/blink.git",
  "https://github.com/brianblakely/omacal.git",
  "https://github.com/brianblakely/omahud.git",
  "https://github.com/brianblakely/omaled.git",
  "https://github.com/brianblakely/omanews.git",
  "https://github.com/brianblakely/omanote.git",
  "https://github.com/brianblakely/omasnap.git",
  "https://github.com/brianblakely/omastonk.git",
  "https://github.com/brianblakely/peek.git",
  "https://github.com/mwikala/omarchy-world-time.git",
  "https://github.com/brianblakely/omadoro.git",
  "https://github.com/nightdevil00/bt.codecs.git",
  "https://github.com/yuters/omarchy-flight-radar.git",
  "https://github.com/brianblakely/omarchy-codex-notifications.git",
  "https://github.com/keithnyc/omanetwatch.git"
]
let passed = 0

function test(name, callback) {
  callback()
  passed += 1
  process.stdout.write(`ok ${passed} - ${name}\n`)
}

test("plugins.txt contains the fifteen locally curated standalone URLs in deterministic order", () => {
  assert.equal(registry.endsWith("\n"), true)
  assert.deepEqual(registry.trimEnd().split("\n"), expectedUrls)
})

test("workflow refreshes after plugins.txt changes and on demand", () => {
  assert.match(workflow, /^on:\n {2}push:\n {4}paths:\n {6}- plugins\.txt\n {2}workflow_dispatch:\n/m)
  assert.doesNotMatch(workflow, /\bpull_request:/)
  assert.doesNotMatch(workflow, /\bschedule:/)
})

test("workflow grants the least repository permission needed to write README", () => {
  assert.match(workflow, /^permissions:\n {2}contents: write\n/m)
  assert.equal((workflow.match(/\bcontents:\s*write\b/g) || []).length, 1)
})

test("workflow uses the current official checkout major and local generator", () => {
  assert.match(workflow, /uses: actions\/checkout@v6/)
  assert.match(workflow, /name: Generate the alphabetized catalog table/)
  assert.match(workflow, /run: node scripts\/generate-plugin-catalog\.mjs/)
  assert.equal((workflow.match(/\buses:/g) || []).length, 1)
})

test("only runtime uses the external marketplace registry", () => {
  assert.equal(generator.split(marketplaceRegistryUrl).length - 1, 0)
  assert.equal(backend.split(marketplaceRegistryUrl).length - 1, 1)
})

test("workflow rejects unrelated changes and stages only README before pushing", () => {
  assert.match(workflow, /git status --porcelain --untracked-files=all -- \. '\:\(exclude\)README\.md'/)
  const addTargets = [...workflow.matchAll(/^\s*git add -- (.+)$/gm)]
    .map(match => match[1])
  assert.deepEqual(addTargets, ["README.md"])
  assert.match(workflow, /\[\[ "\$\(git diff --cached --name-only\)" == "README\.md" \]\]/)
  assert.match(workflow, /^\s*git push$/m)
})

test("README exposes exactly one marker-owned generated catalog region", () => {
  assert.equal(
    readme.split("<!-- BEGIN GENERATED PLUGIN CATALOG -->").length - 1,
    1
  )
  assert.equal(
    readme.split("<!-- END GENERATED PLUGIN CATALOG -->").length - 1,
    1
  )
  assert.match(
    readme,
    /Generated by scripts\/generate-plugin-catalog\.mjs from plugins\.txt; sorted alphabetically by plugin name\./
  )

  const generated = readme.slice(
    readme.indexOf("<!-- BEGIN GENERATED PLUGIN CATALOG -->"),
    readme.indexOf("<!-- END GENERATED PLUGIN CATALOG -->")
  )
  const rows = generated.split("\n")
    .filter(line => line.startsWith("| ["))
  const urls = rows.map(line => {
    const match = line.match(/\]\(<(https:[^>]+)>\)/u)
    assert.ok(match, `could not parse generated catalog URL: ${line}`)
    return match[1]
  })
  const identities = urls.map(url => {
    const parsed = new URL(url)
    return parsed.hostname === "github.com" ? url.toLowerCase() : url
  })
  assert.equal(new Set(identities).size, identities.length)
  assert.deepEqual(urls.slice().sort(), expectedUrls.slice().sort())

  const names = rows
    .map(line => {
      const match = line.match(/^\| \[((?:\\.|[^\]])+)\]\(<https:/u)
      assert.ok(match, `could not parse generated catalog row: ${line}`)
      return match[1].replace(/\\(.)/gu, "$1")
    })
  const alphabetized = names.slice().sort((first, second) => {
    const firstFolded = first.toLowerCase()
    const secondFolded = second.toLowerCase()
    if (firstFolded < secondFolded) return -1
    if (firstFolded > secondFolded) return 1
    if (first < second) return -1
    if (first > second) return 1
    return 0
  })
  assert.deepEqual(names, alphabetized)
})

process.stdout.write(`${passed} catalog workflow tests passed\n`)
